### ISSUE TITLE
RT no longer responding with the exception of !rt help

### ISSUE THREAD

**Issue by pzerou** [WilliamWelsh/RottenTomatoes#1]
Invited the bot and all appeared well the its response to '!rt help' but I can't get it to respond to other queries / listings outlined in the README

Looks like a cool bot. Definitely cherish RT ratings over ImDB

 :)

**Comment by WilliamWelsh** [comment]
Try it again, for some reason my virtual machine that I host my bots on needed to be restarted.

**Comment by WilliamWelsh** [comment]
![image](https://user-images.githubusercontent.com/16886888/78509263-f6d2e600-775a-11ea-80b0-28333f3d6e02.png)

**Comment by WilliamWelsh** [comment]
![image](https://user-images.githubusercontent.com/16886888/78509285-05210200-775b-11ea-82e9-315d02b8092c.png)

**Comment by WilliamWelsh** [comment]
Any update?

**Comment by pzerou** [comment]
Yay! Search and Choose functionality working again. (pardon the late reply)

**!rt upcoming & box office** seem problematic, but that may be very much related to the Covid cancellations. Anyway, my use of the bot is primarily the searched movie listings -- so cheers, many thanks!

**Comment by WilliamWelsh** [comment]
No problem. Regarding **!rt upcoming & box office**, the website has since been updated since the original creation of the bot, and it's much more difficult to scrape data, I've been looking for a workaround for ages, but have been fruitless. If you need any more help, you can add me on Discord (below), I can respond much faster.

Reverse#1193

**Comment by pzerou** [comment]
Thanks! I use this as a Rating Embed for a 'movie club' style discord server. So don't consider me a +1 for any revisions regarding 'upcoming/boxoffice' -- the rating embed already works great for my need 👍 

_unrelated:_ if I have a feature request for 'auto-deleting' the search results embed after **choose number** selection has been made -- where would you prefer that posted?

**Comment by WilliamWelsh** [comment]
> _unrelated:_ if I have a feature request for 'auto-deleting' the search results embed after **choose number** selection has been made -- where would you prefer that posted?

Anywhere is fine, just somewhere I can see it. A new issue or a Discord DM will suffice. That's a good idea though. I had kept it in case they wanted to a choose a different movie, but yeah. Sometimes the search results can get lengthy. I'll implement this :)

**Comment by WilliamWelsh** [comment]
Implemented in https://github.com/WilliamWelsh/RottenTomatoes/commit/3c5e430841d9d47f924535fb5c3436814e35936d (and bot is updated)

**Comment by pzerou** [comment]
Very Awesome!

Works like a charm. Home run with the other small changes too.
